name: "Deploy2K8s Action"
description: "Interacts with kubernetes clusters on eks by `kubectl` and `helm` commands."
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: "docker"
  image: "Dockerfile"
